### ISSUE TITLE
Why use var?

### ISSUE THREAD

**Issue by utvara** [choco-hire/backend-exercise-Giulliano-B#1]
@giubueno Is there any specific reason for using var here?

https://github.com/choco-hire/backend-exercise-Giulliano-B/blob/667aba247a10a50a09d74447e51504bfb3aa35a6/src/utils.ts#L5

**Comment by giubueno** [comment]
I forgot to change it back, I was doing something else and didn't want to pay attention at the moment and end up forgetting to fix it back. A simple let was enough. I even stopped the lint on purpose. 🤔

**Comment by utvara** [comment]
yeah, I saw that there was a deliberate intent :)
